apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: my-inference-scenario
  annotations:
    scenarios.ai.sap.com/name: "churn-model-inference"
    scenarios.ai.sap.com/description: "Scenario to serve the trained churn prediction model."
    executables.ai.sap.com/name: "churn-model-serving"
    executables.ai.sap.com/description: "Serving executable for churn model artifact."
labels:
  ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: model_artifact
        type: string
  template:
    spec:
      containers:
        - name: inference-container
          image: "docker.io/myrepo/churn-model-serving:latest"
          args: ["--model", "{{inputs.parameters.model_artifact}}"]
  resourcePlan: starter
