apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pmrp-delay-predictor-serving
  annotations:
    scenarios.ai.sap.com/name: "pMRP Delay Prediction"
    scenarios.ai.sap.com/description: "Inference scenario for predictive MRP shipment delay model"
    executables.ai.sap.com/name: "pmrp-delay-predictor-serving"
    executables.ai.sap.com/description: "Model serving for pMRP shipment delay prediction"
  labels:
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter
    spec:
      predictor:
        minReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/yourrepo/pmrp-delay-predictor:latest
            args: ["--model", "/models/delay_predictor_model"]
            ports:
              - containerPort: 9001
                protocol: TCP
